### ISSUE TITLE
Size of replaced files is twice as it should be and replaced file is invalid

### ISSUE THREAD

**Issue by dcourcel** [billziss-gh/sshfs-win#143] opened 2020-01-13 01:21 UTC
**Versions where I have the problem :**
- winfsp-1.5.20002 (2019.3)
- sshfs-win-3.5.19106-x64

**No problems with the stable versions or with older winFsp :**
- winfsp-1.5.20002 (2019.3)
- sshfs-win-2.7.17334-x64
or
- winfsp-1.5.19192 (2019.3 B2)
- sshfs-win-3.5.19106-x64 or sshfs-win-2.7.17334-x64

When I copy and replace an existing file on the server, it is not replaced properly. The resulting file size is the double of the original file. When I do hexdump on the file, I noticed that it contains a number of null characters equals to the file size plus the content of the file after.
For example, I created a text file containing the characters "allo" (ascii code : 0x61 0x6c 0x6c 0x6f, file size : 4 bytes). I copied it on the server, then I do _hexdump_ of the file on the server. I got this :
```
# hexdump textfile.txt
0000000 6c61 6f6c
0000004
```
Then, I copied it again, Windows asked me to replace the file, I say yes, and I do hexdump again on the server. This time, I got this :
```
# hexdump textfile.txt
0000000 0000 0000 6c61 6f6c
0000008
```
The file is now 8 bytes with a number of null characters equal to the original file size.
Very not often, but sometimes, when I copy a range of files, even without replacing a file, the last file of the list is copied with it's double size with null characters at the begining.
My hypothesis is that the server is opening the file with truncate mode and do a _seek_ to the size of the file. I think _seek_ will write null characters if it is performed past the end of the file.

I also have the same problem without using sshfs-win.exe with the following command (It is the command sshfs-win.exe launches) :
```
"sshfs.exe" "-f" "-opassword_stdin" "-opassword_stdout" "-orellinks" "-ofstypename=SSHFS" "-oUserKnownHostsFile=/dev/null" "-oStrictHostKeyChecking=no" "-ouid=-1,gid=-1" "--VolumePrefix=\sshfs\<username>@<DomainName>!22222\share" "-oPort=22222" "<username>@<DomainName>:share" "X:"
```

**Comment by billziss-gh** [comment] 2020-01-25 00:05
I apologize for the late response.

Since you mention that this problem does not happen with previous versions of WinFsp, I mention a couple of recent PRs that may (or may not) be related:

- A WinFsp PR related to `O_APPEND`: billziss-gh/winfsp#261.
- A new WinFsp PR that seems to be related to the previous one and claims data corruption: billziss-gh/winfsp#272.

**Comment by billziss-gh** [comment] 2020-01-27 22:11
@dcourcel 

I suspect that the billziss-gh/winfsp#272 PR may resolve this issue. I will produce a build with this patch and place it somewhere for you to download and confirm that the problem is fixed. Is that possible for you to do?

**Comment by billziss-gh** [comment] 2020-01-27 23:42
@dcourcel 

Please try the following build and let me know if it resolves the issue for you:

https://github.com/billziss-gh/winfsp/releases/download/untagged-5762cf5402bfea78473f/winfsp-1.6.20027.msi

**Comment by dcourcel** [comment] 2020-01-28 01:26
Sure, I can try it. I agree the problem described in the PR seems the same as I have.

I can't download the msi file. I get 404 not found. Is it the good link or is there a concept of private and public releases on github?

**Comment by billziss-gh** [comment] 2020-01-28 02:09
@dcourcel please try this alternative location which should work:

http://www.secfs.net/winfsp-1.6.20027.msi

**Comment by dcourcel** [comment] 2020-01-28 02:18
ok, I will try it tomorrow. This link works.

**Comment by billziss-gh** [comment] 2020-01-29 01:25
Thank you for verifying. Closing this.

**Closed by billziss-gh** 2020-01-29 01:25 UTC
